#baseURL = 'http://xrd.org.uk/'
baseURL = 'https://crossroadschurch.netlify.app/'
languageCode = 'en-us'
title = 'Crossroads Church'
theme = ["ananke"]

[params]
custom_css = ["custom.css","special.css"]

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/charlesnbev"

[[params.ananke_socials]]
name = "CMS"
url = "/admin"
